#!/bin/bash
#
# Perform necessary oneacct-export setup steps
# prior to installing package.
#

PROGNAME=$(basename $0)

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

# stop sidekiq service
service oneacct-export-sidekiq stop
# stop cron service
service oneacct-export-cron stop

exit 0
